import { Token } from "./BrandStyle";

export const LightPalette: Token[] = [
  {
    token: "--bg-base",
    hex: "#ffffff",
    rgb: "rgb(255, 255, 255)",
    hsl: "hsl(0, 0%, 100%)",
    label: "White Base",
    usage: "Page background",
  },
  {
    token: "--bg-surface",
    hex: "#f4f4f5",
    rgb: "rgb(244, 244, 245)",
    hsl: "hsl(240, 5%, 96%)",
    label: "Off-White Surface",
    usage: "Cards, panels, modals",
  },
  {
    token: "--bg-elevated",
    hex: "#e4e4e7",
    rgb: "rgb(228, 228, 231)",
    hsl: "hsl(240, 6%, 90%)",
    label: "Light Elevated",
    usage: "Hover states, dividers",
  },
  {
    token: "--text-primary",
    hex: "#09090b",
    rgb: "rgb(9, 9, 11)",
    hsl: "hsl(240, 10%, 4%)",
    label: "Near-Black Primary",
    usage: "All primary body and heading text",
  },
  {
    token: "--text-secondary",
    hex: "#52525b",
    rgb: "rgb(82, 82, 91)",
    hsl: "hsl(240, 5%, 34%)",
    label: "Dark Grey Secondary",
    usage: "Muted labels, captions, metadata",
  },
  {
    token: "--text-disabled",
    hex: "#a1a1aa",
    rgb: "rgb(161, 161, 170)",
    hsl: "hsl(240, 5%, 65%)",
    label: "Disabled",
    usage: "Placeholder text, disabled states",
  },
  {
    token: "--border",
    hex: "#e4e4e7",
    rgb: "rgb(228, 228, 231)",
    hsl: "hsl(240, 6%, 90%)",
    label: "Subtle Border",
    usage: "1px card and input borders",
  },
  {
    token: "--ring",
    hex: "#18181b",
    rgb: "rgb(24, 24, 27)",
    hsl: "hsl(240, 6%, 10%)",
    label: "Focus Ring",
    usage: "Keyboard focus indicators",
  },
  {
    token: "--shadow",
    hex: "rgba(0,0,0,0.08)",
    rgb: "rgba(0, 0, 0, 0.08)",
    hsl: "hsla(0, 0%, 0%, 0.08)",
    label: "Card Shadow",
    usage: "Subtle elevation on cards",
  },
];

export const DarkPalette: Token[] = [
  {
    token: "--bg-base",
    hex: "#18181b",
    rgb: "rgb(24, 24, 27)",
    hsl: "hsl(240, 6%, 10%)",
    label: "Charcoal Base",
    usage: "Page background",
  },
  {
    token: "--bg-surface",
    hex: "#27272a",
    rgb: "rgb(39, 39, 42)",
    hsl: "hsl(240, 4%, 16%)",
    label: "Charcoal Surface",
    usage: "Cards, panels, modals",
  },
  {
    token: "--bg-elevated",
    hex: "#3f3f46",
    rgb: "rgb(63, 63, 70)",
    hsl: "hsl(240, 5%, 26%)",
    label: "Charcoal Elevated",
    usage: "Hover states, dividers",
  },
  {
    token: "--text-primary",
    hex: "#e8e8e8",
    rgb: "rgb(232, 232, 232)",
    hsl: "hsl(0, 0%, 91%)",
    label: "Off-White Primary",
    usage: "All primary body and heading text",
  },
  {
    token: "--text-secondary",
    hex: "#9a9a9a",
    rgb: "rgb(154, 154, 154)",
    hsl: "hsl(0, 0%, 60%)",
    label: "Off-White Secondary",
    usage: "Muted labels, captions, metadata",
  },
  {
    token: "--text-disabled",
    hex: "#555555",
    rgb: "rgb(85, 85, 85)",
    hsl: "hsl(0, 0%, 33%)",
    label: "Disabled",
    usage: "Placeholder text, disabled states",
  },
  {
    token: "--border",
    hex: "#3f3f46",
    rgb: "rgb(63, 63, 70)",
    hsl: "hsl(240, 5%, 26%)",
    label: "Subtle Border",
    usage: "1px card and input borders",
  },
  {
    token: "--ring",
    hex: "#e8e8e8",
    rgb: "rgb(232, 232, 232)",
    hsl: "hsl(0, 0%, 91%)",
    label: "Focus Ring",
    usage: "Keyboard focus indicators",
  },
  {
    token: "--shadow",
    hex: "rgba(0,0,0,0.35)",
    rgb: "rgba(0, 0, 0, 0.35)",
    hsl: "hsla(0, 0%, 0%, 0.35)",
    label: "Card Shadow",
    usage: "Subtle elevation on cards",
  },
];

export const StatusColoursList = [
  {
    label: "Error",
    prefix: "error",
    lightHex: "#fee2e2",
    lightRgb: "rgb(254, 226, 226)",
    lightHsl: "hsl(0, 93%, 94%)",
    darkHex: "#7f1d1d",
    darkRgb: "rgb(127, 29, 29)",
    darkHsl: "hsl(0, 63%, 31%)",
  },
  {
    label: "Success",
    prefix: "success",
    lightHex: "#dcfce7",
    lightRgb: "rgb(220, 252, 231)",
    lightHsl: "hsl(141, 84%, 93%)",
    darkHex: "#14532d",
    darkRgb: "rgb(20, 83, 45)",
    darkHsl: "hsl(142, 61%, 20%)",
  },
  {
    label: "Warning",
    prefix: "warning",
    lightHex: "#fef3c7",
    lightRgb: "rgb(254, 243, 199)",
    lightHsl: "hsl(48, 96%, 89%)",
    darkHex: "#c2410c",
    darkRgb: "rgb(194, 65, 12)",
    darkHsl: "hsl(17, 88%, 40%)",
  },
];
