services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    user: "0:0"
    networks:
      - gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--providers.docker.useBindPortIP=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.httpClientTimeout=300s"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--api.dashboard=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"

  minio:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`storage.${DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  solver:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solver.rule=Host(`solver.${DOMAIN}`)"
      - "traefik.http.routers.solver.entrypoints=websecure"
      - "traefik.http.routers.solver.tls.certresolver=myresolver"
      - "traefik.http.services.solver.loadbalancer.server.port=8000"

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=${BACKEND_PORT}"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=${FRONTEND_PORT}"

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

watchtower:
  image: containrrr/watchtower
  container_name: watchtower
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --interval 30 --cleanup

# simulator:
#     build:
#       context: ./apps/simulator
#       dockerfile: simulator.Dockerfile
#     image: ${DOCKER_REGISTRY}/${PROJECT_NAME}-simulator:latest
#     networks:
#       - gateway
#       - internal
#     depends_on:
#       postgres:
#         condition: service_healthy
#     profiles:
#       - dev-docker
#       - server
