site_name: UMTAS Documentation
site_url: https://cos301-se-2026.github.io/UMTAS/
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/images/VigilOWL.png
  favicon: assets/images/VigilOWL.png
  icon:
    logo: material/owl
  palette:
    scheme: default
    primary: white
    accent: black
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - drawio
  - swagger-ui-tag

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - tables
