global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "nestjs-backend"
    static_configs:
      - targets: ["backend:3001"]
  - job_name: "python-solver"
    static_configs:
      - targets: ["solver:8000"]
