global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: gateway
    httpClientTimeout: 300s
    useBindPortIP: true

certificatesResolvers:
  myresolver:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
