name: Deploy MkDocs
on:
  push:
    branches:
      - main
      - setup-docs
    paths:
      - "wiki"
      - ".github/workflows/deploy-docs.yml"
  gollum:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fetch latest wiki changes
        run: |
          cd wiki
          git fetch origin master
          git checkout origin/master

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install -r wiki/requirements.txt

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --config-file wiki/mkdocs.yml --force
